### Function to summarize data based on tapply()

### USAGE: collapse by an index/factor (in this case the rownames)
### dat <- apply(dat, 2, collapseData, ind=rownames(dat))

### USAGE: Pass an alternative function
### ann <- apply(ann, 2, collapseData, ind=rownames(ann),
###             func=function(x) x[1] )

### ALSO:
### collapsedValues <- apply(ann, 2, collapseData, ind=rownames(ann), func='[',1 )

### General collapsing function
collapseData <- function(x, ind, func=mean,  ...) {
        tapply(X=x, INDEX=ind, FUN=func, ...)
}

### ### To collapse data.frames generated by select() using keys as index
### collapseSelectOutput <- function(dat, keyCol=1,  glue="; ", ...) {
###     apply(dat, 2, collapseData, ind=dat[,keyCol],
###           func=function(x) paste(unique(x), collapse=glue))
### }

collapseSelectOutput <- function(dat, keyCol=1,  glue="; ", ...) {
    if (is.matrix(dat)) {
        apply(dat, 2, collapseData, ind=dat[,keyCol],
              func=function(x) paste(unique(x), collapse=glue))
    } else if (is.data.frame(dat)) {
        sapply(dat, collapseData, ind=dat[,keyCol],
               func=function(x) paste(unique(x), collapse=glue))
    } else stop("This function only works on matrices and data.frames")
}
